### ISSUE TITLE
Update from Cypress 6 to Cypress 8

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css#113]
### Describe the new a11y feature or project enhancement

We'd like to update Checka11y.css to use Cypress 8 rather than Cypress 6 so we can remain up to date with Cypress and make use of new features if needed

### Describe the solution you'd like

Upgrade to Cypress 8

### Link(s)

N/A

**Comment by jackdomleo7** [comment]
I tried updating to npm7 in a previous PR but couldn't because of an issue with the Cypress tests not running 😕

**Comment by jackdomleo7** [comment]
That would be really useful! Thanks @tannerdolby !

**Comment by tannerdolby** [comment]
I haven't got around to this yet, but here is a link for reference when I get started.

https://docs.cypress.io/guides/references/migration-guide

**Comment by tannerdolby** [comment]
I apologize for the delay on this @jackdomleo7!

I got around to rewriting some of the tests in Jest, turns out the majority of the tests require `::after` or `::before` Pseudo element selectors which causes quite a big problem because `jsdom` [doesnt support ::before and ::after](https://github.com/jsdom/jsdom/issues/1928) to allow for getting the `content` property from a pseudo element. Recreating the browser environment works but if the selectors require grabbing `::before` or `::after` and specifically `content` then converting to Jest might require some major workaround as the bulk of tests are asserting against the `content` property of pseudo elements.

In plain js we can grab the `content` property using `window` and [`getComputedStyle()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) like this:

```js
const el = document.querySelector(".some-node");
console.log(window.getComputedStyle(el, ":after").content); // the value of content property
console.log(window.getComputedStyle(el, ":after").getPropertyValue("content"); // ditto
```

This issue of selecting pseudo elements is solved for us when using Cypress as they have the really helpful `.after("prop_name")` method. This discussion might sway us to just stay with Cypress instead of converting like we discussed in #117.

**Comment by jackdomleo7** [comment]
Hi @tannerdolby, absolutely no worries (there is no time limit - except for the fact that a person will automatically be unassigned from an issue after 3 months of inactivity 🙂).

That is really interesting and really useful to know! I think based on this, then I agree, we should stick with Cypress because it seems to be the best tool for the job. Thank you.
