### ISSUE TITLE
Minified version is not being generated correctly

### ISSUE THREAD

**Issue by alvaromontoro** [jackdomleo7/Checka11y.css#63]
### Details

The minified version is not being generated correctly because it is created but then overwritten by the expanded version.

If you run `npm run build`, it only generates checka11y.css but not checka11y.min.css

### What is Expected?

When you run `npm run build` both checka11y.css and checka11y.min.css are created.

### What is actually happening?

This is happening because there is a small misconfiguration in the  package.json. The output of the minified version doesn't have the `.min` in the name.

**Comment by alvaromontoro** [comment]
Created PR #64 to address this issue.

**Comment by jackdomleo7** [comment]
I'm a little confused, there was no intention to create a minified file just yet, didn't seem like it would serve much purpose, so I didn't configure it 🙂 If you're referring to the below script:

```
"build:expanded": "node-sass src/checka11y.scss ./checka11y.css --output-style compressed && node-sass ./checka11y.css ./checka11y.css --output-style expanded && npx postcss checka11y.css --use autoprefixer --replace --no-map"
```

I had to compress checka11y.scss into checka11y.css, then expand checka11y.css into checka11y.css because the SCSS was putting non-important comments (I.e. comment that don't look like this `/*! ... */`) in random places. So doing this method meant it got rid of the non-important comments first.

If you have a fix around that so the script is simpler, I'd be happy to see what you suggest. I'm not sure a minified stylesheet will serve much purpose since this stylesheet is meant for dev environment only. 😊

**Comment by jackdomleo7** [comment]
Sorry, this isn't a bug, it's intentional 🙂. Will close this issue and linked PR until we have an urgent need for a minified stylesheet.

**Comment by alvaromontoro** [comment]
Ooops. I saw the reference to `checka11y.min.css` in the README instructions, but it was not being generated when doing `npm run build`, so I thought it was an issue with the package.json. 

I guess it makes sense that it is not generated as it's a dev environment only thing (I'll cancel the PR). The README should be updated to remove that reference, or there may be more PRs like this.

**Comment by alvaromontoro** [comment]
You closed it as I was pressing the send button :P
Thanks!

**Comment by jackdomleo7** [comment]
I'd be happy for you to correct the README though? That'd be useful 🙂 Good spot!
