### ISSUE TITLE
Live Demo Example?

### ISSUE THREAD

**Issue by impressivewebs** [jackdomleo7/Checka11y.css#67]
Looks like a nice project, and I know the website is still in the works, but it might be nice to add a simple demo page that demonstrates how this works, even if it's just temporary prior to the website launch.

**Comment by jackdomleo7** [comment]
Sure, feel free to make a temporary demo page if you want. I'm currently tied up on something else in another project, so the website won't be soon.

Whoever wants to do this:
- Only work in the `gh-pages` branch because this is the website
- Use the `test/index.html` file in the `master` branch as a reference when doing this

**Comment by jackdomleo7** [comment]
Completed in #78
