### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by Lewiscowles1986** [jackdomleo7/Checka11y.css#72]
Hello again. Thanks for writing this. It's interesting.

### Describe the new a11y feature or project enhancement

In order to help people contribute to this repository, it would be great to use GitHub to check all pull-requests automatically.

### Describe the solution you'd like

Automatically running lint and tests on all incoming PR's

### Link(s)

N/A

### Other

I'm willing to write this for you.

**Comment by jackdomleo7** [comment]
Hi. When I get chance, I was going to research how to automatically run the tests in some sort of pipeline, so the PR can't be merged until all tests pass. In terms of linting, I thought this would be more difficult because it will need to do a commit automatically.

But, if you can do this, then that would be super helpful!

**Comment by Lewiscowles1986** [comment]
Can you expand on

>  In terms of linting, I thought this would be more difficult because it will need to do a commit automatically.

I'll supply instructions with the PR for adding guards for the primary branch

**Comment by Lewiscowles1986** [comment]
As for Linting I can make it a separate PR, but I don't think it needs to commit. Linting at CI should be the whole repo, but a git reset in a github action, could equally as well have it check the changed files.

**Comment by Lewiscowles1986** [comment]
Linting PR is not merged 😉  feel like re-opening. We just got CI in without linting so-far

**Comment by jackdomleo7** [comment]
Reopening for @Lewiscowles1986 and linting 😉
